package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Book generated by hbm2java
 */
@Entity(name = "BOOKS")
public class Book implements java.io.Serializable {

	@Id
	@Column(name = "BOOKID", nullable = false)
	public int bookid;
	@Column(name = "LANGID", nullable = false)
	public int langid;
	@Column(name = "BOOKNAME", nullable = false, length = 2000000000)
	public String bookname;
	@Column(name = "UNITSINBOOK", nullable = false)
	public int unitsinbook;
	@Column(name = "PARTS", nullable = false, length = 2000000000)
	public String parts;
	@Column(name = "UNITFROM", nullable = false)
	public int unitfrom;
	@Column(name = "PARTFROM", nullable = false)
	public int partfrom;
	@Column(name = "UNITTO", nullable = false)
	public int unitto;
	@Column(name = "PARTTO", nullable = false)
	public int partto;

	public Book() {
	}
}
