package com.zwstudio.lolly.domain;

// Generated 2014-10-12 21:44:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Dictionary generated by hbm2java
 */
@Entity(name = "VDICTIONARIES")
public class Dictionary implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "LANGIDFROM")
    public Integer langidfrom;
    @Column(name = "LANGIDTO")
    public Integer langidto;
    @Column(name = "SEQNUM")
    public Integer seqnum;
    @Column(name = "DICTTYPENAME")
    public String dicttypename;
    @Column(name = "DICTNAME")
    public String dictname;
    @Column(name = "URL")
    public String url;
    @Column(name = "CHCONV")
    public String chconv;
    @Column(name = "AUTOMATION")
    public String automation;
    @Column(name = "AUTOJUMP")
    public Integer autojump;
    @Column(name = "DICTTABLE")
    public String dicttable;
    @Column(name = "TRANSFORM_WIN")
    public String transformWin;
    @Column(name = "TRANSFORM_MAC")
    public String transformMac;
    @Column(name = "WAIT")
    public Integer wait;
    @Column(name = "TEMPLATE")
    public String template;

    public Dictionary() {
    }

}
