package com.zwstudio.lolly.domain;

// Generated 2014-10-12 21:44:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * UnitWord generated by hbm2java
 */
@Entity(name = "LANGWORDS")
public class LangWord implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "LANGID", nullable = false)
    public int langid;
    @Column(name = "WORD", nullable = false)
    public String word;
    @Column(name = "LEVEL", nullable = false)
    public int level;

	public LangWord() {
	}
}
