package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Language generated by hbm2java
 */
@Entity(name = "VLANGUAGES")
public class Language implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "LANGNAME")
    public String langname;
    @Column(name = "VOICE")
    public String voice;
    @Column(name = "USTEXTBOOKID")
    public int ustextbookid;

    public Language() {
    }
}
