package com.zwstudio.lolly.domain;

// Generated 2014-10-4 23:22:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity(name = "LANGUAGES")
public class Language implements java.io.Serializable {

	@Id
	@Column(name = "LANGID", nullable = false)
	public int langid;
	@Column(name = "LANGNAME", nullable = false, length = 2000000000)
	public String langname;
	@Column(name = "CHNNAME", nullable = false, length = 2000000000)
	public String chnname;
	@Column(name = "VOICE", length = 2000000000)
	public String voice;
	@Column(name = "CURBOOKID")
	public Integer curbookid;
	@Column(name = "ENGNAME", length = 2000000000)
	public String engname;


	public Language() {
	}
}
