package com.zwstudio.lolly.domain;

// Generated 2014-10-12 21:44:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * UnitWord generated by hbm2java
 */
@Entity(name = "VTEXTBOOKWORDS")
public class TextbookWord implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "LANGID", nullable = false)
    public int langid;
    @Column(name = "TEXTBOOKNAME")
    public int textbookname;
    @Column(name = "UNIT")
    public int unit;
    @Column(name = "PART")
    public int part;
    @Column(name = "SEQNUM")
    public int seqnum;
    @Column(name = "WORD")
    public String word;
    @Column(name = "NOTE")
    public String note;

	public TextbookWord() {
	}
}
