package com.zwstudio.lolly.domain;

// Generated 2014-10-12 21:44:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * UnitWord generated by hbm2java
 */
@Entity(name = "UNITWORDS")
public class UnitWord implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "TEXTBOOKID", nullable = false)
    public int textbookid;
    @Column(name = "UNIT", nullable = false)
    public int unit;
    @Column(name = "PART", nullable = false)
    public int part;
    @Column(name = "SEQNUM", nullable = false)
    public int seqnum;
    @Column(name = "WORD", nullable = false)
    public String word;
    @Column(name = "NOTE")
    public String note;

	public UnitWord() {
	}
}
