package com.zwstudio.lolly.domain;

// Generated 2014-10-12 21:44:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * WordUnit generated by hbm2java
 */
@Entity(name = "WORDSBOOK")
public class WordUnit implements java.io.Serializable {

    @Id
    @Column(name = "ID", nullable = false)
    public int id;
    @Column(name = "BOOKID", nullable = false)
    public int bookid;
    @Column(name = "UNIT", nullable = false)
    public int unit;
    @Column(name = "PART", nullable = false)
    public int part;
    @Column(name = "SEQNUM", nullable = false)
    public int seqnum;
    @Column(name = "WORD", nullable = false, length = 2000000000)
    public String word;
    @Column(name = "NOTE", length = 2000000000)
    public String note;

	public WordUnit() {
	}
}
